
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCXXCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --c++ 
      
      The output was:
      1
      c++.exe: error: unrecognized command-line option '--c++'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --ec++ 
      
      The output was:
      1
      c++.exe: error: unrecognized command-line option '--ec++'; did you mean '-Weffc++'?
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      c++.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      c++.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCXXCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCXXCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --c++ 
      
      The output was:
      1
      c++.exe: error: unrecognized command-line option '--c++'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --ec++ 
      
      The output was:
      1
      c++.exe: error: unrecognized command-line option '--ec++'; did you mean '-Weffc++'?
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      c++.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      c++.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCXXCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
      c++.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
      c++.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "try_compile-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-qym69l"
      binary: "//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-qym69l"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-qym69l'
        
        Run Build Command(s): G:/applications/jetbrains/CLion/bin/ninja/win/x64/ninja.exe -v cmTC_8aa66
        [1/2] G:\\applications\\scoop\\apps\\mingw\\13.2.0-rt_v11-rev0\\bin\\c++.exe    -o CMakeFiles\\cmTC_8aa66.dir\\CMakeCXXCompilerABI.cpp.obj -c G:\\applications\\jetbrains\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp
        FAILED: CMakeFiles/cmTC_8aa66.dir/CMakeCXXCompilerABI.cpp.obj 
        G:\\applications\\scoop\\apps\\mingw\\13.2.0-rt_v11-rev0\\bin\\c++.exe    -o CMakeFiles\\cmTC_8aa66.dir\\CMakeCXXCompilerABI.cpp.obj -c G:\\applications\\jetbrains\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp
        Assembler messages:\x0d
        Fatal error: can't create CMakeFiles\\cmTC_8aa66.dir\\CMakeCXXCompilerABI.cpp.obj: Invalid argument\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "G:/applications/jetbrains/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working CXX compiler: G:/applications/scoop/apps/mingw/13.2.0-rt_v11-rev0/bin/c++.exe"
    directories:
      source: "//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-7b3wve"
      binary: "//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-7b3wve"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Debian/home/jing/allprojects/clang/Games/Dino/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-7b3wve'
        
        Run Build Command(s): G:/applications/jetbrains/CLion/bin/ninja/win/x64/ninja.exe -v cmTC_40f63
        [1/2] G:\\applications\\scoop\\apps\\mingw\\13.2.0-rt_v11-rev0\\bin\\c++.exe    -o CMakeFiles\\cmTC_40f63.dir\\testCXXCompiler.cxx.obj -c \\\\wsl.localhost\\Debian\\home\\jing\\allprojects\\clang\\Games\\Dino\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-7b3wve\\testCXXCompiler.cxx
        FAILED: CMakeFiles/cmTC_40f63.dir/testCXXCompiler.cxx.obj 
        G:\\applications\\scoop\\apps\\mingw\\13.2.0-rt_v11-rev0\\bin\\c++.exe    -o CMakeFiles\\cmTC_40f63.dir\\testCXXCompiler.cxx.obj -c \\\\wsl.localhost\\Debian\\home\\jing\\allprojects\\clang\\Games\\Dino\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-7b3wve\\testCXXCompiler.cxx
        Assembler messages:\x0d
        Fatal error: can't create CMakeFiles\\cmTC_40f63.dir\\testCXXCompiler.cxx.obj: Invalid argument\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
